#!/usr/bin/env python3
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]

def patch_once(path,old,new):
    text=path.read_text(encoding='utf-8')
    count=text.count(old)
    if count!=1: raise SystemExit(f'guard failed {path}: {count} matches for {old[:80]!r}')
    path.write_text(text.replace(old,new,1),encoding='utf-8')

core=ROOT/'src-tauri/resources/ui/physical_lab_model_builder.py'
anchor='''def _flatten_numeric(value: Any, prefix: str = "") -> dict[str, float]:\n'''
shape='''def _shape_signature(value: Any) -> Any:\n    if isinstance(value, dict):\n        return {str(key): _shape_signature(child) for key, child in sorted(value.items(), key=lambda item: str(item[0]))}\n    if isinstance(value, list):\n        return {"type": "list", "length": len(value), "items": [_shape_signature(child) for child in value]}\n    if value is None:\n        return "null"\n    if isinstance(value, bool):\n        return "bool"\n    if isinstance(value, (int, float)) and not isinstance(value, bool):\n        return "number"\n    if isinstance(value, str):\n        return "string"\n    return type(value).__name__\n\n\ndef _flatten_numeric(value: Any, prefix: str = "") -> dict[str, float]:\n'''
patch_once(core,anchor,shape)
old='''    same_structure = json.dumps(original_outputs, sort_keys=True, separators=(",", ":")) == json.dumps(adapter_outputs, sort_keys=True, separators=(",", ":")) if not common else set(original_numeric) == set(adapter_numeric)\n    equivalent = bool(numeric_equivalent and same_structure)\n'''
new='''    same_structure = _shape_signature(original_outputs) == _shape_signature(adapter_outputs)\n    numeric_paths_match = set(original_numeric) == set(adapter_numeric)\n    equivalent = bool(numeric_equivalent and same_structure and numeric_paths_match)\n'''
patch_once(core,old,new)
patch_once(core,'''        "same_structure": same_structure,\n        "numeric_values_compared": len(common),\n''','''        "same_structure": same_structure,\n        "numeric_paths_match": numeric_paths_match,\n        "numeric_values_compared": len(common),\n''')

val=ROOT/'scripts/model_builder_validation.py'
patch_once(val,'''        assert check["equivalent"] is True\n        assert check["max_abs_diff"] == 0.0\n''','''        assert check["equivalent"] is True\n        assert check["same_structure"] is True\n        assert check["numeric_paths_match"] is True\n        assert check["max_abs_diff"] == 0.0\n''')

js=ROOT/'web/app.js'
patch_once(js,'''  renderModelBuilderControls(spec);\n''','''  renderModelBuilderControls(modelBuilderBundle?.model_spec||spec);\n''')
old_sync='''function syncModelSpecFromReview(){\n  const spec=currentModelBuilderSpec();if(!spec){toast('ModelSpec JSON is invalid.',true);return null}\n  document.querySelectorAll('[data-model-review]').forEach(card=>{const i=Number(card.dataset.modelReview);const p=spec.parameters?.[i];if(!p)return;const get=name=>card.querySelector(`[data-mb-review-field="${name}"]`)?.value??'';p.label=get('label').trim()||p.name;p.unit=get('unit').trim()||null;p.control=get('control');p.default=parseModelBuilderDefault(get('default'),p.type);p.min=nullableNumber(get('min'));p.max=nullableNumber(get('max'));});\n  el('modelBuilderSpec').value=JSON.stringify(spec,null,2);return spec;\n}\n'''
new_sync='''function invalidateModelBuilderGeneratedArtifacts(){modelBuilderBundle=null;modelBuilderPreviewData=null;modelBuilderValidationData=null}\nfunction syncModelSpecFromReview(){\n  const spec=currentModelBuilderSpec();if(!spec){toast('ModelSpec JSON is invalid.',true);return null}\n  document.querySelectorAll('[data-model-review]').forEach(card=>{const i=Number(card.dataset.modelReview);const p=spec.parameters?.[i];if(!p)return;const get=name=>card.querySelector(`[data-mb-review-field="${name}"]`)?.value??'';p.label=get('label').trim()||p.name;p.unit=get('unit').trim()||null;p.control=get('control');p.default=parseModelBuilderDefault(get('default'),p.type);p.min=nullableNumber(get('min'));p.max=nullableNumber(get('max'));});\n  el('modelBuilderSpec').value=JSON.stringify(spec,null,2);invalidateModelBuilderGeneratedArtifacts();return spec;\n}\n'''
patch_once(js,old_sync,new_sync)
patch_once(js,"if(el('modelBuilderSpec'))el('modelBuilderSpec').onchange=renderModelBuilder;\n","if(el('modelBuilderSpec'))el('modelBuilderSpec').onchange=()=>{invalidateModelBuilderGeneratedArtifacts();renderModelBuilder()};\n")

readme=ROOT/'README.md'
old_para='''It combines numerical-error analysis, Monte Carlo/statistical physics, stochastic simulation, nonlinear dynamics, oscillation/integration, and a RADIA-backed **magnet → electron trajectory → radiation** workflow. Physical Lab adds the engineering and research-software layer around those solvers: isolated environments, pinned source revisions, Safe/Full execution, scientific smoke tests, measurement provenance, V&V/UQ, model-specific requirement scorecards, automated refinement/replicate campaigns, convergence/cost analysis, robust-design summaries, measured/model comparison, batch planning, run provenance, and reproducibility exports.\n'''
new_para=old_para+'''\nThe **Unreleased Research Model Builder MVP** adds a creator path alongside the ten built-in Lab families: a trusted local `.py` model can be statically inspected without execution, converted into a human-reviewed `ModelSpec`, wrapped by a generated adapter, previewed through deterministic controls/plots, checked for original↔adapter interface equivalence, and stored as a provenance-tracked model bundle inside a canonical `.physlab` Project.\n'''
patch_once(readme,old_para,new_para)
patch_once(readme,'''| What physics does it cover? | Numerical error, Ising/Monte Carlo, random walk/QMC, chaos/Lyapunov analysis, oscillators/integration, Kerr relativity, solar-system dynamics, multilayer lattice/phonons, RADIA magnetics, undulator radiation |\n''','''| What physics does it cover? | Numerical error, Ising/Monte Carlo, random walk/QMC, chaos/Lyapunov analysis, oscillators/integration, Kerr relativity, solar-system dynamics, multilayer lattice/phonons, RADIA magnetics, undulator radiation |\n| Can students bring their own Python model? | **Yes, in the Unreleased Model Builder MVP:** static AST analysis → human-reviewed ModelSpec → generated wrapper/UI → explicit trusted local preview → adapter-equivalence check → Project model bundle |\n''')
section='''## Research Model Builder — Unreleased MVP\n\nPhysical Lab now includes a native **Model Builder** creation surface based on the principle **Preserve the science. Standardize the interface. Automate the bridge.** The MVP is intentionally narrower than an unrestricted AI code generator:\n\n```text\ntrusted local model.py\n        ↓\nstatic AST analysis (no import / no execution)\n        ↓\nentry / parameters / outputs / dependencies\n        ↓\nhuman parameter + unit + range review\n        ↓\nphysical-lab-model-spec-v1\n        ↓\nadapter.py + deterministic ui.json + tests/provenance\n        ↓\nexplicit trusted local Preview\n        ↓\noriginal ↔ adapter equivalence\n        ↓\ncanonical Project models/<bundle-id>/\n```\n\nGeneration never overwrites the selected source file. A generated bundle contains an `original_model.py` snapshot plus separate `adapter.py`, `model.json`, `ui.json`, `tests.json` and `provenance.json`, each with source/model fingerprints where applicable. Slider bounds are never invented automatically: ranges and scientific units remain human-confirmed metadata.\n\n`Analyze` and `Generate` do not execute the selected model. `Preview` and `Validate Adapter` are separate trusted-local-code actions with a fixed timeout, bounded output capture and no shell-command execution path. The current MVP is **not a sandbox for arbitrary untrusted Internet code** and does not provide public/server Python execution.\n\nAdapter equivalence verifies that the wrapper preserves the selected source snapshot's interface/output structure for a declared test case. It does **not** establish correctness of equations, units, assumptions, numerical method, calibration, experimental validity, safety, compliance or certification. See `docs/RESEARCH_MODEL_BUILDER_MVP.md`.\n\n'''
patch_once(readme,'## Evidence-First Engineering Systems Workbench\n',section+'## Evidence-First Engineering Systems Workbench\n')

changelog=ROOT/'CHANGELOG.md'
insert='''### Added — Research Model Builder MVP\n- Added a native **Model Builder** creation surface for trusted local Python research models without turning the Builder into an eleventh built-in physics Lab.\n- Added static AST inspection for top-level functions, candidate parameters/outputs, imports, source SHA-256 and execution-risk warnings; static analysis does not import or execute the selected source.\n- Added human-reviewed `physical-lab-model-spec-v1` metadata with explicit labels, units, controls, defaults and user-confirmed slider ranges.\n- Added wrapper-not-rewrite generation of `original_model.py`, `adapter.py`, `model.json`, `ui.json`, `tests.json` and `provenance.json` with deterministic fingerprints.\n- Added deterministic ModelSpec rendering for number, slider, toggle, dropdown and text controls plus scalar, numeric-array, automatic x-y and structured-JSON preview output.\n- Added explicit trusted local Preview and original↔adapter equivalence checks with timeout/output bounds; adapter equivalence compares output shape/type signatures and numeric paths/values.\n- Added canonical `.physlab` Project model storage under `models/<bundle-id>/` plus `models/index.json`; legacy workspaces must be migrated before Builder bundles can be registered.\n- Added deterministic and wiring validations proving Analyze/Generate do not execute student source and that execution remains an explicit local action.\n\n### Model Builder boundary\nResearch Model Builder automates the interface around a student model, not the scientific judgment inside it. It does not silently rewrite source equations, infer authoritative units/ranges, establish scientific correctness, provide a security sandbox for arbitrary untrusted Internet code, or establish experimental validation, safety, compliance or certification. Public/server arbitrary-Python execution, publishing, model-library/fork services and browser/WASM execution remain deferred.\n\n'''
patch_once(changelog,'### Restored — first-class bundled scientific Labs\n',insert+'### Restored — first-class bundled scientific Labs\n')

print('Model Builder hardening/doc patch applied')
