#!/usr/bin/env python3
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def patch_once(path: Path, old: str, new: str) -> None:
    text = path.read_text(encoding="utf-8")
    count = text.count(old)
    if count != 1:
        raise SystemExit(f"guard failed for {path}: expected one anchor, found {count}: {old[:80]!r}")
    path.write_text(text.replace(old, new, 1), encoding="utf-8")


# Rust module registration + commands.
lib = ROOT / "src-tauri/src/lib.rs"
patch_once(lib, "mod research;\n", "mod research;\nmod model_builder;\n")
old_handler = "research::adapter_statuses, research::export_reproducibility_package, research::list_run_snapshots, research::compare_run_snapshots, research::list_campaigns, research::campaign_action, cancel_task])"
new_handler = "research::adapter_statuses, research::export_reproducibility_package, research::list_run_snapshots, research::compare_run_snapshots, research::list_campaigns, research::campaign_action,\n            research::save_model_builder_bundle, model_builder::model_builder_choose_source, model_builder::model_builder_analyze, model_builder::model_builder_generate, model_builder::model_builder_run, model_builder::model_builder_validate, model_builder::model_builder_open_bundle, cancel_task])"
patch_once(lib, old_handler, new_handler)

# macOS native file picker for the local .py source.
bridge = ROOT / "src-tauri/src/model_builder.rs"
anchor = "#[tauri::command]\npub fn model_builder_analyze(app: AppHandle, source_path: String) -> Result<Value, String> {"
choose = r'''#[tauri::command]
pub fn model_builder_choose_source() -> Result<String, String> {
    let output = Command::new("/usr/bin/osascript")
        .args([
            "-e",
            "POSIX path of (choose file with prompt \"Choose a trusted local Python research model\")",
        ])
        .output()
        .map_err(|e| e.to_string())?;
    if !output.status.success() {
        let detail = String::from_utf8_lossy(&output.stderr).trim().to_string();
        return Err(if detail.is_empty() {
            "Python file selection was cancelled.".into()
        } else {
            detail
        });
    }
    let path = String::from_utf8_lossy(&output.stdout).trim().to_string();
    if !path.to_ascii_lowercase().ends_with(".py") {
        return Err("Research Model Builder MVP accepts a .py source file.".into());
    }
    Ok(path)
}

#[tauri::command]
pub fn model_builder_analyze(app: AppHandle, source_path: String) -> Result<Value, String> {'''
patch_once(bridge, anchor, choose)

# Canonical Project storage for generated bundles.
research = ROOT / "src-tauri/src/research.rs"
patch_once(research, '        "campaigns",\n    ] {', '        "campaigns",\n        "models",\n    ] {')
command_anchor = "#[tauri::command]\npub fn create_workspace(app: AppHandle, name: String) -> Result<WorkspaceSummary, String> {"
project_save = r'''fn save_model_builder_bundle_to_dir(
    app: &AppHandle,
    workspace_id: &str,
    bundle_path: &str,
) -> Result<Value, String> {
    let (project_dir, canonical) = resolve_project_dir(app, workspace_id)?;
    if !canonical {
        return Err("Research Model Builder saves only to canonical .physlab Projects. Migrate the legacy workspace first.".into());
    }
    let allowed_root = app_root(app)?.join("model-builder").join("bundles");
    let allowed_root = allowed_root.canonicalize().map_err(|e| e.to_string())?;
    let source = PathBuf::from(bundle_path)
        .canonicalize()
        .map_err(|e| e.to_string())?;
    if !source.is_dir() || !source.starts_with(&allowed_root) {
        return Err("Only bundles generated by this Physical Lab Model Builder can be saved to a Project.".into());
    }
    let provenance = read_json(&source.join("provenance.json"))?;
    if provenance.get("schema").and_then(Value::as_str) != Some("physical-lab-model-bundle-v1") {
        return Err("Model bundle provenance schema is invalid.".into());
    }
    let model_spec = read_json(&source.join("model.json"))?;
    if model_spec.get("schema").and_then(Value::as_str) != Some("physical-lab-model-spec-v1") {
        return Err("Model bundle ModelSpec schema is invalid.".into());
    }
    let bundle_id = provenance
        .get("bundle_id")
        .and_then(Value::as_str)
        .map(safe_slug)
        .filter(|value| !value.is_empty())
        .ok_or("Model bundle id is missing")?;
    let destination = project_dir.join("models").join(&bundle_id);
    fs::create_dir_all(&destination).map_err(|e| e.to_string())?;
    for filename in [
        "original_model.py",
        "adapter.py",
        "model.json",
        "ui.json",
        "tests.json",
        "provenance.json",
    ] {
        let input = source.join(filename);
        if !input.is_file() {
            return Err(format!("Generated model bundle is missing {filename}"));
        }
        fs::copy(&input, destination.join(filename)).map_err(|e| e.to_string())?;
    }
    let project = read_json(&project_dir.join("project.json"))?;
    let record = json!({
        "schema":"physical-lab-research-model-v1",
        "bundle_id":bundle_id,
        "project_id":project.get("project_id").and_then(Value::as_str).unwrap_or(""),
        "name":model_spec.get("metadata").and_then(|value| value.get("name")).and_then(Value::as_str).unwrap_or("Research Model"),
        "description":model_spec.get("metadata").and_then(|value| value.get("description")).and_then(Value::as_str).unwrap_or(""),
        "entry_function":model_spec.get("compute").and_then(|value| value.get("entry_function")).and_then(Value::as_str).unwrap_or(""),
        "source_sha256":provenance.get("source_sha256"),
        "adapter_sha256":provenance.get("adapter_sha256"),
        "model_spec_sha256":provenance.get("model_spec_sha256"),
        "stored_path":format!("models/{bundle_id}"),
        "registered_at":now_iso(),
        "generation_policy":"wrapper-not-rewrite",
        "boundary":"Project membership records provenance and a reviewable model bundle. It does not establish scientific validity, experimental validation, safety, compliance or certification."
    });
    let index_path = project_dir.join("models").join("index.json");
    let mut index = if index_path.is_file() {
        read_json(&index_path).unwrap_or_else(|_| json!({}))
    } else {
        json!({})
    };
    if index.get("schema").and_then(Value::as_str) != Some("physical-lab-model-index-v1") {
        index = json!({"schema":"physical-lab-model-index-v1","models":{},"updated_at":null});
    }
    if index.get("models").and_then(Value::as_object).is_none() {
        index["models"] = json!({});
    }
    if let Some(rows) = index.get_mut("models").and_then(Value::as_object_mut) {
        rows.insert(bundle_id.clone(), record.clone());
    }
    index["updated_at"] = Value::String(now_iso());
    write_json(&index_path, &index)?;
    touch_project_after_direct_write(&project_dir, true)?;
    Ok(record)
}

#[tauri::command]
pub fn save_model_builder_bundle(
    app: AppHandle,
    workspace_id: String,
    bundle_path: String,
) -> Result<Value, String> {
    save_model_builder_bundle_to_dir(&app, &workspace_id, &bundle_path)
}

#[tauri::command]
pub fn create_workspace(app: AppHandle, name: String) -> Result<WorkspaceSummary, String> {'''
patch_once(research, command_anchor, project_save)

# Packaged Python core.
conf = ROOT / "src-tauri/tauri.conf.json"
patch_once(
    conf,
    '      "resources/ui/physical_lab_local_ai.py": "ui/physical_lab_local_ai.py"\n',
    '      "resources/ui/physical_lab_local_ai.py": "ui/physical_lab_local_ai.py",\n      "resources/ui/physical_lab_model_builder.py": "ui/physical_lab_model_builder.py"\n',
)

# Native navigation + UI surface.
html = ROOT / "web/index.html"
patch_once(
    html,
    '        <button class="nav-item" data-view="labs"><span>◌</span>Physics Labs</button>\n',
    '        <button class="nav-item" data-view="labs"><span>◌</span>Physics Labs</button>\n        <button class="nav-item" data-view="modelbuilder"><span>＋</span>Model Builder</button>\n',
)
model_view = r'''
      <section id="modelBuilderView" class="view">
        <div class="research-hero"><div><div class="eyebrow">PRESERVE THE SCIENCE • AUTOMATE THE BRIDGE</div><h2>Research Model Builder</h2><p>Turn a trusted local Python research model into a reviewable ModelSpec, deterministic interface and Project-ready model bundle without silently rewriting the scientific source.</p></div><div class="research-badge" id="modelBuilderProjectBadge">No project selected</div></div>
        <div class="tool-panel"><div class="form-row"><label>Python source<input id="modelBuilderSource" placeholder="/Users/.../my_model.py" /></label><button id="modelBuilderChooseSource" class="secondary">Choose .py</button><button id="modelBuilderAnalyze" class="primary">Analyze</button></div><p class="hint">Analyze is static AST inspection only: the selected file is not imported or executed.</p></div>
        <div class="two-col">
          <div class="tool-panel"><h3>Model analysis</h3><div id="modelBuilderAnalysis" class="model-builder-analysis"><div class="empty-state">Choose a Python model and analyze it.</div></div></div>
          <div class="tool-panel"><h3>Parameter review</h3><p class="hint">Confirm labels, units and controls. Physical Lab never invents slider bounds: sliders require explicit min/max.</p><div id="modelBuilderParameterReview"><div class="empty-state">Detected parameters will appear here.</div></div><button id="modelBuilderApplyReview" class="secondary">Apply review to ModelSpec</button></div>
        </div>
        <div class="tool-panel"><div class="section-head"><div><h3>Advanced ModelSpec</h3><p>Structured interface contract. Edit directly when the detected structure needs correction.</p></div><button id="modelBuilderGenerate" class="primary">Generate Adapter + UI</button></div><textarea id="modelBuilderSpec" class="code-textarea" rows="18" spellcheck="false" placeholder="Analyze a model to generate a candidate ModelSpec."></textarea></div>
        <div class="tool-panel"><div class="section-head"><div><h3>Generated model bundle</h3><p>Original snapshot, adapter, ModelSpec, UI spec, tests and provenance remain separate.</p></div><button id="modelBuilderOpenBundle" class="secondary">Open Bundle Folder</button></div><div id="modelBuilderBundle"><div class="empty-state">Generate a model bundle first.</div></div></div>
        <div class="two-col">
          <div class="tool-panel"><h3>Deterministic preview</h3><div id="modelBuilderRuntimeControls"><div class="empty-state">Generate a bundle to render ModelSpec controls.</div></div><label class="trust-check"><input id="modelBuilderTrusted" type="checkbox" /> I trust this local Python source and understand Preview/Validate will execute its bundled snapshot on this Mac.</label><div class="card-actions"><button id="modelBuilderPreview" class="primary">Run Preview</button><button id="modelBuilderValidate" class="secondary">Validate Adapter</button><button id="modelBuilderSave" class="secondary">Save to Active Project</button></div><p class="hint">Adapter equivalence checks interface conversion only. It is not scientific validation of equations, assumptions, units or reference truth.</p></div>
          <div class="tool-panel"><h3>Preview output</h3><div id="modelBuilderPreviewOutput"><div class="empty-state">No preview run yet.</div></div><h3>Adapter validation</h3><div id="modelBuilderValidationOutput"><div class="empty-state">No adapter-equivalence check yet.</div></div></div>
        </div>
      </section>

'''
patch_once(html, '      <section id="runtimeView" class="view">\n', model_view + '      <section id="runtimeView" class="view">\n')

# Frontend state, view map, renderer and actions.
js = ROOT / "web/app.js"
patch_once(
    js,
    "let campaignData = [];\n",
    "let campaignData = [];\nlet modelBuilderAnalysis = null;\nlet modelBuilderBundle = null;\nlet modelBuilderPreviewData = null;\nlet modelBuilderValidationData = null;\n",
)
patch_once(
    js,
    "labs:['labsView','Physics Labs','Install, open and switch between computational models.'],runtime:",
    "labs:['labsView','Physics Labs','Install, open and switch between computational models.'],modelbuilder:['modelBuilderView','Research Model Builder','Preserve the science. Standardize the interface. Automate the bridge.'],runtime:",
)
patch_once(
    js,
    "renderRuntimeSummary(); renderDependencies(); renderResearch(); renderSettings(); applyUiSettings(); bindDynamic(); renderTasks(); applySearch();",
    "renderRuntimeSummary(); renderDependencies(); renderResearch(); renderModelBuilder(); renderSettings(); applyUiSettings(); bindDynamic(); renderTasks(); applySearch();",
)
model_js = r'''
function currentModelBuilderSpec(){
  const raw=(el('modelBuilderSpec')?.value||'').trim();
  if(!raw)return null;
  try{return JSON.parse(raw)}catch(_){return null}
}
function nullableNumber(raw){const text=String(raw??'').trim();if(!text)return null;const value=Number(text);return Number.isFinite(value)?value:null}
function modelBuilderDefaultText(value){if(value===null||value===undefined)return '';if(typeof value==='string')return value;return JSON.stringify(value)}
function parseModelBuilderDefault(raw,type){const text=String(raw??'').trim();if(!text)return null;if(type==='number'){const n=Number(text);return Number.isFinite(n)?n:null}if(type==='boolean')return text==='true';try{return JSON.parse(text)}catch(_){return text}}
function renderModelBuilder(){
  const badge=el('modelBuilderProjectBadge');const ws=activeWorkspace();if(badge)badge.textContent=ws?`Project: ${ws.name}`:'No project selected';
  const analysisNode=el('modelBuilderAnalysis');
  if(analysisNode){
    if(!modelBuilderAnalysis)analysisNode.innerHTML='<div class="empty-state">Choose a Python model and analyze it.</div>';
    else{
      const warnings=modelBuilderAnalysis.warnings||[];const functions=modelBuilderAnalysis.functions||[];const imports=modelBuilderAnalysis.imports||[];
      analysisNode.innerHTML=`<div class="model-builder-kpis"><div><span>Entry</span><strong>${esc(modelBuilderAnalysis.candidate_entry||'Needs review')}</strong></div><div><span>Functions</span><strong>${functions.length}</strong></div><div><span>Imports</span><strong>${imports.length}</strong></div><div><span>SHA-256</span><strong>${esc((modelBuilderAnalysis.source_sha256||'').slice(0,12))}</strong></div></div><div class="builder-tags">${imports.map(x=>`<code>${esc(x)}</code>`).join('')||'<span class="hint">No imports detected.</span>'}</div>${warnings.length?`<div class="builder-warnings">${warnings.map(w=>`<div class="callout"><strong>${esc(w.kind)}</strong><br/>${esc(w.message)}</div>`).join('')}</div>`:'<div class="callout good-callout">No static execution-risk warning was detected. This is not a security guarantee.</div>'}<p class="hint">${esc(modelBuilderAnalysis.execution_boundary||'')}</p>`;
    }
  }
  const spec=currentModelBuilderSpec();const review=el('modelBuilderParameterReview');
  if(review){
    const params=spec?.parameters||[];
    review.innerHTML=params.length?params.map((p,i)=>`<article class="model-param-review" data-model-review="${i}"><div class="category">${esc(p.name)}</div><div class="form-grid"><label>Label<input data-mb-review-field="label" value="${esc(p.label||p.name)}" /></label><label>Unit<input data-mb-review-field="unit" value="${esc(p.unit||'')}" placeholder="unknown" /></label><label>Control<select data-mb-review-field="control"><option ${p.control==='number'?'selected':''}>number</option><option ${p.control==='slider'?'selected':''}>slider</option><option ${p.control==='toggle'?'selected':''}>toggle</option><option ${p.control==='dropdown'?'selected':''}>dropdown</option><option ${p.control==='text'?'selected':''}>text</option></select></label><label>Default<input data-mb-review-field="default" value="${esc(modelBuilderDefaultText(p.default))}" /></label><label>Min<input data-mb-review-field="min" type="number" step="any" value="${esc(p.min??'')}" /></label><label>Max<input data-mb-review-field="max" type="number" step="any" value="${esc(p.max??'')}" /></label></div></article>`).join(''):'<div class="empty-state">Detected parameters will appear here.</div>';
  }
  const bundleNode=el('modelBuilderBundle');
  if(bundleNode){bundleNode.innerHTML=modelBuilderBundle?`<div class="model-bundle-card"><div><div class="category">${esc(modelBuilderBundle.bundle_id||'MODEL BUNDLE')}</div><h4>${esc(modelBuilderBundle.model_spec?.metadata?.name||'Research Model')}</h4><p class="dataset-path">${esc(modelBuilderBundle.bundle_path||'')}</p></div><div class="builder-tags"><code>source ${esc((modelBuilderBundle.source_sha256||'').slice(0,12))}</code><code>adapter ${esc((modelBuilderBundle.adapter_sha256||'').slice(0,12))}</code><code>ModelSpec ${esc((modelBuilderBundle.model_spec_sha256||'').slice(0,12))}</code></div></div>`:'<div class="empty-state">Generate a model bundle first.</div>'}
  renderModelBuilderControls(spec);
  const previewNode=el('modelBuilderPreviewOutput');if(previewNode)previewNode.innerHTML=modelBuilderPreviewData?renderModelBuilderOutputs(modelBuilderPreviewData.outputs||{}):'<div class="empty-state">No preview run yet.</div>';
  const validationNode=el('modelBuilderValidationOutput');if(validationNode){validationNode.innerHTML=modelBuilderValidationData?`<div class="validation-banner ${modelBuilderValidationData.equivalent?'good-callout':'bad-callout'}"><strong>${modelBuilderValidationData.equivalent?'INTERFACE EQUIVALENT':'NEEDS REVIEW'}</strong><span>Compared ${modelBuilderValidationData.numeric_values_compared||0} numeric values · max |Δ| ${esc(modelBuilderValidationData.max_abs_diff??'—')}</span></div><p class="hint">${esc(modelBuilderValidationData.boundary||'')}</p>`:'<div class="empty-state">No adapter-equivalence check yet.</div>'}
}
function syncModelSpecFromReview(){
  const spec=currentModelBuilderSpec();if(!spec){toast('ModelSpec JSON is invalid.',true);return null}
  document.querySelectorAll('[data-model-review]').forEach(card=>{const i=Number(card.dataset.modelReview);const p=spec.parameters?.[i];if(!p)return;const get=name=>card.querySelector(`[data-mb-review-field="${name}"]`)?.value??'';p.label=get('label').trim()||p.name;p.unit=get('unit').trim()||null;p.control=get('control');p.default=parseModelBuilderDefault(get('default'),p.type);p.min=nullableNumber(get('min'));p.max=nullableNumber(get('max'));});
  el('modelBuilderSpec').value=JSON.stringify(spec,null,2);return spec;
}
function renderModelBuilderControls(spec){
  const node=el('modelBuilderRuntimeControls');if(!node)return;const params=spec?.parameters||[];
  if(!modelBuilderBundle||!params.length){node.innerHTML=modelBuilderBundle?'<div class="hint">This ModelSpec declares no interactive parameters.</div>':'<div class="empty-state">Generate a bundle to render ModelSpec controls.</div>';return}
  node.innerHTML=`<div class="model-runtime-controls">${params.map(p=>modelBuilderControlHtml(p)).join('')}</div>`;
  document.querySelectorAll('[data-model-param-range]').forEach(input=>input.oninput=()=>{const out=document.querySelector(`[data-model-param-value="${CSS.escape(input.dataset.modelParamRange)}"]`);if(out)out.textContent=input.value});
}
function modelBuilderControlHtml(p){
  const name=esc(p.name),label=esc(p.label||p.name),unit=p.unit?` <span>${esc(p.unit)}</span>`:'';const value=p.default??'';
  if(p.control==='slider'&&p.min!==null&&p.max!==null)return `<label class="model-runtime-control">${label}${unit}<div class="range-row"><input data-model-param data-model-param-range="${name}" data-param-name="${name}" type="range" min="${esc(p.min)}" max="${esc(p.max)}" step="any" value="${esc(value??p.min)}"/><output data-model-param-value="${name}">${esc(value??p.min)}</output></div></label>`;
  if(p.control==='toggle')return `<label class="model-runtime-control toggle-row"><input data-model-param data-param-name="${name}" type="checkbox" ${value?'checked':''}/>${label}${unit}</label>`;
  if(p.control==='dropdown'&&Array.isArray(p.options))return `<label class="model-runtime-control">${label}${unit}<select data-model-param data-param-name="${name}">${p.options.map(v=>`<option value="${esc(v)}" ${String(v)===String(value)?'selected':''}>${esc(v)}</option>`).join('')}</select></label>`;
  const type=p.control==='number'||p.type==='number'?'number':'text';return `<label class="model-runtime-control">${label}${unit}<input data-model-param data-param-name="${name}" type="${type}" ${type==='number'?'step="any"':''} value="${esc(value)}"/></label>`;
}
function collectModelBuilderParameters(){
  const params={};for(const input of document.querySelectorAll('[data-model-param]')){const name=input.dataset.paramName;if(!name)continue;if(input.type==='checkbox')params[name]=input.checked;else if(input.type==='number'||input.type==='range'){const n=Number(input.value);if(!Number.isFinite(n))throw new Error(`Parameter ${name} needs a finite number.`);params[name]=n}else params[name]=input.value}return params;
}
function numericArray(value){return Array.isArray(value)&&value.length>1&&value.every(v=>typeof v==='number'&&Number.isFinite(v))}
function sparkline(values){const w=280,h=90,min=Math.min(...values),max=Math.max(...values),span=Math.max(1e-12,max-min);const points=values.map((v,i)=>`${(i/(values.length-1)*w).toFixed(2)},${(h-(v-min)/span*h).toFixed(2)}`).join(' ');return `<svg class="builder-sparkline" viewBox="0 0 ${w} ${h}" role="img" aria-label="numeric output sparkline"><polyline points="${points}" fill="none" stroke="currentColor" stroke-width="2"/></svg>`}
function xyPlot(x,y){const w=520,h=180,x0=Math.min(...x),x1=Math.max(...x),y0=Math.min(...y),y1=Math.max(...y),xs=Math.max(1e-12,x1-x0),ys=Math.max(1e-12,y1-y0);const points=x.map((v,i)=>`${((v-x0)/xs*w).toFixed(2)},${(h-(y[i]-y0)/ys*h).toFixed(2)}`).join(' ');return `<div class="builder-xy"><svg viewBox="0 0 ${w} ${h}" role="img" aria-label="automatic x-y preview"><polyline points="${points}" fill="none" stroke="currentColor" stroke-width="2"/></svg><small>x ${x0.toPrecision(4)} → ${x1.toPrecision(4)} · y ${y0.toPrecision(4)} → ${y1.toPrecision(4)}</small></div>`}
function renderModelBuilderOutputs(outputs){const entries=Object.entries(outputs||{});const arrays=entries.filter(([,v])=>numericArray(v));const auto=arrays.length>=2&&arrays[0][1].length===arrays[1][1].length?`<div class="builder-auto-plot"><div class="category">AUTO X-Y · ${esc(arrays[0][0])} → ${esc(arrays[1][0])}</div>${xyPlot(arrays[0][1],arrays[1][1])}</div>`:'';return `${auto}<div class="model-output-grid">${entries.map(([k,v])=>`<article class="model-output-card"><div class="category">${esc(k)}</div>${typeof v==='number'?`<strong>${esc(v)}</strong>`:numericArray(v)?`${sparkline(v)}<small>${v.length} values · min ${Math.min(...v).toPrecision(5)} · max ${Math.max(...v).toPrecision(5)}</small>`:`<pre>${esc(JSON.stringify(v,null,2))}</pre>`}</article>`).join('')}</div>`}
async function chooseResearchModelSource(){if(!invoke){toast('File chooser is available in the desktop build.');return}try{const path=await invoke('model_builder_choose_source');el('modelBuilderSource').value=path}catch(e){if(!String(e).toLowerCase().includes('cancel'))toast(String(e),true)}}
async function analyzeResearchModel(){const sourcePath=el('modelBuilderSource').value.trim();if(!sourcePath){toast('Choose a .py source first.',true);return}if(!invoke){toast('Static model analysis is available in the desktop build.');return}try{modelBuilderAnalysis=await invoke('model_builder_analyze',{sourcePath});modelBuilderBundle=null;modelBuilderPreviewData=null;modelBuilderValidationData=null;el('modelBuilderSpec').value=JSON.stringify(modelBuilderAnalysis.candidate_model_spec||{},null,2);renderModelBuilder();toast('Static analysis complete. Source was not executed.')}catch(e){toast(String(e),true)}}
async function generateResearchModel(){if(!invoke)return;const sourcePath=el('modelBuilderSource').value.trim();const spec=syncModelSpecFromReview()||currentModelBuilderSpec();if(!sourcePath||!spec){toast('Analyze the source and review ModelSpec first.',true);return}try{modelBuilderBundle=await invoke('model_builder_generate',{sourcePath,modelSpec:spec});modelBuilderPreviewData=null;modelBuilderValidationData=null;renderModelBuilder();toast('Adapter and deterministic UI bundle generated without executing the source.')}catch(e){toast(String(e),true)}}
function modelBuilderTrusted(){return !!el('modelBuilderTrusted')?.checked}
async function runResearchModelPreview(){if(!invoke||!modelBuilderBundle){toast('Generate a model bundle first.',true);return}if(!modelBuilderTrusted()){toast('Confirm that you trust this local Python source before execution.',true);return}try{const parameters=collectModelBuilderParameters();modelBuilderPreviewData=await invoke('model_builder_run',{bundlePath:modelBuilderBundle.bundle_path,parameters,trusted:true});renderModelBuilder();toast('Local preview complete.')}catch(e){toast(String(e),true)}}
async function validateResearchModelAdapter(){if(!invoke||!modelBuilderBundle){toast('Generate a model bundle first.',true);return}if(!modelBuilderTrusted()){toast('Confirm that you trust this local Python source before execution.',true);return}try{const parameters=collectModelBuilderParameters();modelBuilderValidationData=await invoke('model_builder_validate',{bundlePath:modelBuilderBundle.bundle_path,parameters,trusted:true});renderModelBuilder();toast(modelBuilderValidationData.equivalent?'Adapter equivalence passed.':'Adapter needs review.',!modelBuilderValidationData.equivalent)}catch(e){toast(String(e),true)}}
async function saveResearchModelToProject(){if(!invoke||!modelBuilderBundle){toast('Generate a model bundle first.',true);return}if(!activeWorkspaceId){toast('Create or select a canonical Project first.',true);return}try{const record=await invoke('save_model_builder_bundle',{workspaceId:activeWorkspaceId,bundlePath:modelBuilderBundle.bundle_path});await refreshResearchBasics();render();toast(`Saved ${record.name||'research model'} to the active Project.`)}catch(e){toast(String(e),true)}}
async function openResearchModelBundle(){if(!invoke||!modelBuilderBundle)return;try{await invoke('model_builder_open_bundle',{bundlePath:modelBuilderBundle.bundle_path})}catch(e){toast(String(e),true)}}

'''
patch_once(js, "function renderTasks(){\n", model_js + "function renderTasks(){\n")
patch_once(
    js,
    "if(el('createWorkspace'))el('createWorkspace').onclick=createProject;\n",
    "if(el('modelBuilderChooseSource'))el('modelBuilderChooseSource').onclick=chooseResearchModelSource;\nif(el('modelBuilderAnalyze'))el('modelBuilderAnalyze').onclick=analyzeResearchModel;\nif(el('modelBuilderApplyReview'))el('modelBuilderApplyReview').onclick=()=>{if(syncModelSpecFromReview())renderModelBuilder()};\nif(el('modelBuilderGenerate'))el('modelBuilderGenerate').onclick=generateResearchModel;\nif(el('modelBuilderPreview'))el('modelBuilderPreview').onclick=runResearchModelPreview;\nif(el('modelBuilderValidate'))el('modelBuilderValidate').onclick=validateResearchModelAdapter;\nif(el('modelBuilderSave'))el('modelBuilderSave').onclick=saveResearchModelToProject;\nif(el('modelBuilderOpenBundle'))el('modelBuilderOpenBundle').onclick=openResearchModelBundle;\nif(el('modelBuilderSpec'))el('modelBuilderSpec').onchange=renderModelBuilder;\n\nif(el('createWorkspace'))el('createWorkspace').onclick=createProject;\n",
)

# Model Builder styling; append only once.
css = ROOT / "web/styles.css"
text = css.read_text(encoding="utf-8")
marker = "/* Research Model Builder MVP */"
if marker in text:
    raise SystemExit("guard failed: Model Builder CSS already present")
text += r'''

/* Research Model Builder MVP */
.code-textarea{width:100%;min-height:280px;background:var(--panel,#fff);color:inherit;border:1px solid var(--border,#dfe3e8);border-radius:12px;padding:14px;font-family:ui-monospace,SFMono-Regular,Menlo,monospace;line-height:1.45;resize:vertical}
.model-builder-kpis{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px;margin-bottom:12px}.model-builder-kpis>div,.model-output-card,.model-bundle-card{border:1px solid var(--border,#dfe3e8);border-radius:12px;padding:12px}.model-builder-kpis span{display:block;font-size:11px;text-transform:uppercase;opacity:.65}.model-builder-kpis strong{display:block;margin-top:4px;overflow-wrap:anywhere}.builder-tags{display:flex;flex-wrap:wrap;gap:6px;margin:8px 0}.builder-tags code{padding:4px 7px;border-radius:8px;background:rgba(127,127,127,.12)}.builder-warnings{display:grid;gap:8px}.good-callout{border-color:#56a36c!important}.bad-callout{border-color:#b45353!important}.model-param-review{border-top:1px solid var(--border,#dfe3e8);padding:12px 0}.model-param-review:first-child{border-top:0}.trust-check{display:flex!important;align-items:flex-start;gap:9px;margin:14px 0;font-size:13px}.trust-check input{margin-top:2px}.model-runtime-controls{display:grid;gap:12px}.model-runtime-control{display:grid;gap:6px}.range-row{display:grid;grid-template-columns:1fr 72px;gap:10px;align-items:center}.range-row output{text-align:right;font-family:ui-monospace,SFMono-Regular,Menlo,monospace}.toggle-row{display:flex;align-items:center;gap:8px}.model-output-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.model-output-card pre{max-height:180px;overflow:auto;white-space:pre-wrap;overflow-wrap:anywhere;font-size:11px}.builder-sparkline,.builder-xy svg{width:100%;height:auto;color:currentColor}.builder-auto-plot{border:1px solid var(--border,#dfe3e8);border-radius:12px;padding:12px;margin-bottom:10px}.builder-xy small{display:block;margin-top:6px;opacity:.7}.validation-banner{display:grid;gap:5px;border:1px solid var(--border,#dfe3e8);border-radius:12px;padding:12px;margin-bottom:8px}.model-bundle-card{display:flex;justify-content:space-between;gap:16px}.model-bundle-card .dataset-path{max-width:720px}@media(max-width:900px){.model-builder-kpis,.model-output-grid{grid-template-columns:1fr 1fr}.model-bundle-card{display:block}}@media(max-width:680px){.model-builder-kpis,.model-output-grid{grid-template-columns:1fr}}
'''
css.write_text(text, encoding="utf-8")

# Self-check and Source Integrity.
self_check = ROOT / "scripts/self_check.py"
patch_once(
    self_check,
    "    'src-tauri/src/main.rs','src-tauri/resources/modules.json','src-tauri/resources/dependencies.json',\n",
    "    'src-tauri/src/main.rs','src-tauri/src/model_builder.rs','src-tauri/resources/modules.json','src-tauri/resources/dependencies.json',\n",
)
patch_once(
    self_check,
    "    'src-tauri/resources/ui/physical_lab_advanced.py','BUILD_PHYSICAL_LAB.command','PACKAGE_RELEASE_DMG.command',\n",
    "    'src-tauri/resources/ui/physical_lab_advanced.py','src-tauri/resources/ui/physical_lab_model_builder.py','BUILD_PHYSICAL_LAB.command','PACKAGE_RELEASE_DMG.command',\n",
)
patch_once(
    self_check,
    "assert 'resources/safe_engine_server.py' in resources\n",
    "assert 'resources/safe_engine_server.py' in resources\nassert 'resources/ui/physical_lab_model_builder.py' in resources\n",
)
patch_once(
    self_check,
    "print('Shared Project surface + Evidence Center: configured')\n",
    "print('Shared Project surface + Evidence Center: configured')\nprint('Research Model Builder: static AST → ModelSpec → adapter → preview/equivalence → Project bundle configured')\n",
)

workflow = ROOT / ".github/workflows/source-integrity.yml"
patch_once(
    workflow,
    "scripts/requirements_verification_validation.py scripts/requirements_verification_wiring_validation.py scripts/v010_release_readiness_validation.py",
    "scripts/requirements_verification_validation.py scripts/requirements_verification_wiring_validation.py scripts/model_builder_validation.py scripts/model_builder_wiring_validation.py scripts/v010_release_readiness_validation.py",
)
patch_once(
    workflow,
    "          rustfmt --edition 2021 --emit stdout src-tauri/src/lib.rs >/dev/null\n",
    "          rustfmt --edition 2021 --emit stdout src-tauri/src/lib.rs >/dev/null\n          rustfmt --edition 2021 --emit stdout src-tauri/src/model_builder.rs >/dev/null\n",
)
patch_once(
    workflow,
    "          python scripts/requirements_verification_wiring_validation.py\n          python scripts/v010_release_readiness_validation.py\n",
    "          python scripts/requirements_verification_wiring_validation.py\n          python scripts/model_builder_validation.py\n          python scripts/model_builder_wiring_validation.py\n          python scripts/v010_release_readiness_validation.py\n",
)

print("Research Model Builder guarded integration applied")
